# Use postgres/example user/password credentials
# docker-compose build; docker-compose up -d
version: '3.1'

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.7.9
    restart: always
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: user
    ports:
      - "5672:5672"

  send:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 8081:8081
    links:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
#    ports:
#      - 8081:8081
    links:
      - rabbitmq
      - postgresql

